### ISSUE TITLE
Create a tool which uses the Harbor REST api to populate data

### ISSUE THREAD

**Issue by vuil** [vuil/harbor#1]
https://github.com/vmware/harbor/blob/4e52b13ea9450491a09f4387b5c1a45b744c2910/contrib/sdk/harbor-py/harborclient/harborclient.py can be used as a model for the tool, or you can just use the sdk directly as well. Don't need anything too fancy here.
Something that can populate X users, Y projects, Z repos deterministically would be good.

**Comment by srm912** [comment]
Merged
