### ISSUE TITLE
Improve test coverage of lwraft-related code

### ISSUE THREAD

**Issue by srm09** [vuil/harbor#38]
UT : sql and lwraft querybuilders
IT : processing of queries from lwraft testdb

**Comment by vuil** [comment]
We need to add a dao/qb_sql_test.go, however trivial they are (This is the UT: sql qb part)

lwraft_test/qb_lwraft_test, should just be qb_test, and made to work identically against both QBs
(IT: processing of queries bit, should apply to both types of QB)

**Comment by srm09** [comment]
This is done, Gerrit patches [one](https://review.ec.eng.vmware.com/#/c/19530/) and [two](https://review.ec.eng.vmware.com/#/c/19647/)
