### ISSUE TITLE
Bug: need better error-check of lwraft results

### ISSUE THREAD

**Issue by vuil** [vuil/harbor#46]
(if issue is a bug, include steps to repro: env settings, branch/commit, etc, where relevant)

especially for empty lists, null entries, etc

**Comment by vuil** [comment]
@srm912 What else needs to be done here?

**Comment by srm09** [comment]
All the checks under the dao/lwraft package are in place. This [patch](https://review.ec.eng.vmware.com/#/c/19561/) has the related changes.
